yarnPath: .yarn/releases/yarn-remote.mjs

preferReuse: true

defaultSemverRangePrefix: ''

enableGlobalCache: true

globalFolder: ../.yarn/berry

packageExtensions:
  octokit@*:
    dependencies:
      '@octokit/webhooks': '*'
