name: Sync directories
description: synchronization directories with excludes

inputs:
  sourceDirectory:
    description: source directory
    default: tmp/source
    required: true
  targetDirectory:
    description: target directory
    default: tmp/target
    required: true

runs:
  using: composite

  steps:
    - name: Sync files to remote repository
      shell: bash
      run: |
        rsync -av --progress --ignore-existing "${{ inputs.sourceDirectory }}" "${{ inputs.targetDirectory }}"
