name: Publish composite action
description: create changelog and publish if applicable

inputs:
  onlyChangelog:
    required: false
    default: 'false'
    description: Should only create changelog without publish
  token:
    required: false
    description: GitHub PAT
  baseCommit:
    required: false
    description: Base commit from which to parse workspace changes
  exclude:
    required: false
    description: Which packages to exclude
    default: 'nothing'

runs:
  using: composite

  steps:
    - name: Generate changelog
      env:
        EXCLUDE: ${{ inputs.exclude }}
      run: |
        for dir in packages/*; do
          if [ -d "$dir" ]; then
            dirname=$(basename "$dir")
            if [[ ! " ${EXCLUDE[@]} " =~ " $dirname " ]]; then
                pushd "$dir" >/dev/null || exit
                php vendor/bin/conventional-changelog
                popd >/dev/null
            else
              echo "Skipping $dir"
            fi
          fi
        done
      shell: bash
