name: Create release branch
description: create release branch

inputs:
  githubToken:
    description: Github token
    required: true
  releaseVersion:
    description: Release version
    required: true

runs:
  using: composite

  steps:
    - name: Create new branch
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      run: |
        branch=release/${{ inputs.releaseVersion }}
        echo "branchName=$branch" >> $GITHUB_OUTPUT
        git checkout -b $branch
        git push --set-upstream origin $branch
