name: Rename directories
description: rename directories

inputs:
  targetDirectory:
    description: working directory
    default: tmp/target
    required: true
  sourceFilename:
    description: dirname to rename
    required: true
  targetFilename:
    description: name to rename
    required: true

runs:
  using: composite

  steps:
    - name: Rename directories
      shell: bash
      working-directory: ${{ inputs.targetDirectory }}
      run: |
        find . -type f -iname "*${{ inputs.sourceFilename }}*" -print0 | while IFS= read -r -d '' file; do
          dir=$(dirname "$file")
          base=$(basename "$file")
          newbase="${base//${{ inputs.sourceFilename }}/${{ inputs.targetFilename }}}"
          if [ "$base" != "$newbase" ]; then
            echo "Renaming: $file -> $dir/$newbase"
            mv -- "$file" "$dir/$newbase"
          fi
        done
