name: reusable release workflow prepare pull request action
description: get commit author; get new branch name; checkout and push new empty branch; git add; git commit; create pull request with inputs.reviewer

inputs:
  githubToken:
    description: github app token
    required: true
  releaseVersion:
    description: new release version
    required: true
  reviewerUsername:
    description: pull-request reviewer username
    required: true

runs:
  using: composite

  steps:
    - name: Create release branch
      shell: bash
      id: createReleaseBranchStep
      run: |
        set -e

        branch="release/${{ inputs.releaseVersion }}"
        git fetch origin
        git switch -c "$branch"
        git push origin "$branch"

        echo "branchName=$branch" >> "$GITHUB_OUTPUT"

    - uses: rees46/workflow/.github/actions/github/pull-request/get-last-author@master
      id: lastPrAuthorStep
      with:
        githubToken: ${{ inputs.githubToken }}

    - uses: rees46/workflow/.github/actions/github/commit/create@master
      with:
        branchName: ${{ steps.createReleaseBranchStep.outputs.branchName }}
        githubToken: ${{ inputs.githubToken }}
        targetRepository: ${{ github.repository }}

- name: Wait for branch to be available
  shell: bash
  run: |
    for i in {1..10}; do
      if git ls-remote --heads origin "refs/heads/${{ inputs.releaseVersion }}" | grep -q "${{ inputs.releaseVersion }}"; then
        echo "Branch is available."
        break
      else
        echo "Branch not yet available. Waiting..."
        sleep 6
      fi
    done
    - uses: rees46/workflow/.github/actions/github/pull-request/create@master
      with:
        targetDirectory: .
        githubToken: ${{ inputs.githubToken }}
        lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
        prTitle: 'Bump version to ${{ inputs.releaseVersion }}'
        prBody: 'Automated version bump'
        branchName: ${{ steps.createReleaseBranchStep.outputs.branchName }}
        reviewerUsername: ${{ inputs.reviewerUsername }}
