name: Publish composite action
description: create changelog and publish if applicable

inputs:
  onlyChangelog:
    required: false
    default: 'false'
    description: Should only create changelog without publish
  npmAuthToken:
    required: false
    description: NPM token for publishing
  token:
    required: true
    description: GitHub PAT
  baseCommit:
    required: true
    description: Base commit from which to parse workspace changes
  exclude:
    required: false
    description: Which workspaces to exclude
    default: 'nothing'


runs:
  using: composite

  steps:
    - name: Generate changelog
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
        BASE_COMMIT: ${{ inputs.baseCommit }}
        EXCLUDE: ${{ inputs.exclude }}
      run: yarn workspaces foreach --since=$BASE_COMMIT^ --exclude=$EXCLUDE --verbose run changelog
      shell: bash

    - name: Publish
      if: inputs.onlyChangelog == 'false'
      env:
        YARN_NPM_AUTH_TOKEN: ${{ inputs.npmAuthToken }}
        BASE_COMMIT: ${{ inputs.baseCommit }}
      run: yarn workspaces foreach --since=$BASE_COMMIT^ --exclude=$EXCLUDE --verbose --topological --no-private npm publish --access public
      shell: bash
