name: Clean directory
description: clean directory with excludes

inputs:
  targetDirectory:
    description: working directory
    default: tmp/target
    required: true
  syncIgnore:
    description: working directory
    default: tmp/target
    required: true

runs:
  using: composite

  steps:
    - name: Clean target directory except excluded files
      shell: bash
      working-directory: ${{ inputs.targetDirectory }}
      env:
        SYNC_IGNORE: ${{ inputs.syncIgnore }}
      run: |
        IFS=',' read -r -a ignored_files <<< "$SYNC_IGNORE"

        exclude_conditions=""
        for ignored_file in "${ignored_files[@]}"; do
          exclude_conditions=" $exclude_conditions ! -name \"$ignored_file\""
        done

        eval find . -mindepth 1 -maxdepth 1 $exclude_conditions -exec rm -rf {} +
