name: Rename directories
description: rename directories

inputs:
  targetDirectory:
    description: working directory
    default: tmp/target
    required: true
  replacementDirnames:
    description: list of dirnames to replace, separated by ',' and '|' - separate source target content\
    default: "source:dirname:1|target:dirname:1,source-dirname-2|target-dirname-2"
    required: true

runs:
  using: composite

  steps:
    - name: Rename directories
      shell: bash
      working-directory: ${{ inputs.targetDirectory }}
      env:
        REPLACEMENT_DIRNAMES: ${{ inputs.replacementDirnames }}
      run: |
        IFS=',' read -r -a replacement_dirnames <<< "$REPLACEMENT_DIRNAMES"

        for replacement_dirname in "${replacement_dirnames[@]}"; do
          IFS='|' read -r old_name new_name <<< "$replacement_dirname"

          find . -depth -type d -iname '*$old_name*' -exec bash -c '
            for dir; do
              newdir=$(echo "$dir" | sed -e "s/$old_name/$new_name/gi")
              if [ "$dir" != "$newdir" ]; then
                echo "Renaming directory: $dir -> $newdir"
                mv "$dir" "$newdir"
              fi
            done
          ' bash {} +
        done
