name: Rename directories
description: rename directories

inputs:
  targetDirectory:
    description: working directory
    default: tmp/target
    required: true
  sourceDirname:
    description: dirname to rename
    required: true
  targetDirname:
    description: name to rename
    required: true

runs:
  using: composite

  steps:
    - name: Rename directories
      shell: bash
      working-directory: ${{ inputs.targetDirectory }}
      run: |
        find . -depth -type d -iname '*${{ inputs.sourceDirname }}*' -exec bash -c '
          for dir; do
            newdir=$(echo "$dir" | sed -e "s/${{ inputs.sourceDirname }}/${{ inputs.targetDirname }}/gi")
            if [ "$dir" != "$newdir" ]; then
              echo "Renaming directory: $dir -> $newdir"
              mv "$dir" "$newdir"
            fi
          done
        ' bash {} +
