name: Create commit
description: create commit

inputs:
  workingDirectory:
    description: Target directory with .git
    required: true
  targetRepository:
    description: Target repository to commit
    required: true
  githubToken:
    description: GitHup token
    required: true
  branchName:
    description: Branch to commit
    required: true

runs:
  using: composite

  steps:
    - name: Commit changes
      uses: planetscale/ghcommit-action@v0.2.0
      working-directory: ${{ inputs.workingDirectory }}
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        repo: ${{ inputs.targetRepository }}
        branch: ${{ inputs.branchName }}
        commit_message: "feat: release"
