name: Create commit
description: create commit

inputs:
  workingDirectory:
    description: Target directory with .git
    required: false
    default: .
  targetRepository:
    description: Target repository to commit
    required: true
  githubToken:
    description: GitHup token
    required: true
  branchName:
    description: Branch to commit
    required: true

runs:
  using: composite

  steps:
    - name: Move working directory to root
      shell: bash
      if: ${{ inputs.excludeTmp != '.' }}
      run: mv -R ${{ inputs.workingDirectory }}/* .

    - name: Commit changes
      uses: planetscale/ghcommit-action@v0.2.0
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        repo: ${{ inputs.targetRepository }}
        branch: ${{ inputs.branchName }}
        commit_message: "feat: release"
