name: Create commit
description: create commit

inputs:
  workingDirectory:
    description: Target directory with .git
    required: true
  targetRepository:
    description: Target repository to commit
    required: false
    default: ${{ github.repository }}
  githubToken:
    description: GitHup token
    required: true
  branchName:
    description: Branch to commit
    required: true
  commitMessage:
    default: "feat: release"
    description: commit message
    required: true
  filePattern:
    description: File pattern used for `git add`. For example `src/*.js`
    required: false
    default: "."

runs:
  using: composite

  steps:
    - name: Commit changes
      uses: planetscale/ghcommit-action@v0.2.0
      working-directory: ${{ inputs.workingDirectory }}
      env:
        GITHUB_TOKEN: ${{ inputs.githubToken }}
      with:
        repo: ${{ inputs.targetRepository }}
        branch: ${{ inputs.branchName }}
        commit_message: ${{ inputs.commitMessage }}
        file_pattern: ${{ inputs.filePattern }}
