name: Composite start JS action
description: Prepare JS action - checkout, generate App token, yarn install

inputs:
  nodeVersion:
    description: Node version to run this workflow. Default 18 as it is in action cache
    default: '18'
    required: false
  appId:
    description: App ID for committing and pushing
    required: true
  appSecret:
    description: App secret for committing changes
    required: true
  workingDirectory:
    required: false
    default: ./
    description: Where the script runs

runs:
  using: composite

  steps:
    - uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.appSecret }}

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ steps.app-token.outputs.token }}
        ref: master

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.nodeVersion }}

    - name: Install
      working-directory: ${{ inputs.workingDirectory }}
      run: yarn install --inline-builds
      shell: bash
