name: reusable repo sync workflow prepare pull request action
description: get commit author; get new branch name; checkout and push new empty branch; git add; git commit; create pull request with inputs.reviewer

inputs:
  appToken:
    description: github app token
    required: false
    default: ''
  reviewerUsername:
    description: pull request reviewer username
    required: false
    default: ''
  targetRepository:
    description: target repository to commit
    required: false
    default: ''

runs:
  using: composite

  steps:
    - uses: rees46/workflow/.github/actions/github/pull-request/get-last-author@master
      id: lastPrAuthorStep
      with:
        githubToken: ${{ inputs.appToken }}
        reviewerUsername: ${{ inputs.reviewerUsername }}

    - uses: rees46/workflow/.github/actions/github/utils/get-new-branch-name@master
      id: newBranchNameStep
      with:
        baseBranchName: 'sync'

    - uses: rees46/workflow/.github/actions/git/checkout-new-branch@master
      with:
        workingDirectory: ${{ env.TARGET_TMP_PATH }}
        branchName: ${{ steps.newBranchNameStep.outputs.branchName }}

    - uses: rees46/workflow/.github/actions/git/add@master
      with:
        workingDirectory: ${{ env.TARGET_TMP_PATH }}
        excludeTmp: true

    - uses: rees46/workflow/.github/actions/github/commit/create@master
      with:
        workingDirectory: ${{ env.TARGET_TMP_PATH }}
        branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
        githubToken: ${{ inputs.appToken }}
        targetRepository: ${{ inputs.targetRepository }}

    - uses: rees46/workflow/.github/actions/git/wait-available-branch@master
      with:
        branchToCheck: ${{ steps.newBranchNameStep.outputs.branchName }}

    - uses: rees46/workflow/.github/actions/github/pull-request/create@master
      with:
        targetRepository: ${{ inputs.targetRepository }}
        reviewerUsername: ${{ inputs.reviewerUsername }}
        targetDirectory: ${{ env.TARGET_TMP_PATH }}
        githubToken: ${{ inputs.appToken }}
        lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
        branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
        prTitle: 'Synchronization PR'
        prBody: 'Automated repository synchronization'
