name: Create pull request on target repo
description: create pull request on target repo

inputs:
  targetDirectory:
    default: tmp/target
    description: Commit author GitGup token
    required: true
  githubToken:
    description: GitHup token
    required: true
  prTitle:
    description: PullRequest title
    default: Automated release
    required: false
  prBody:
    description: PullRequest body
    default: This is an automated pull request
    required: false
  reviewerUsername:
    description: PullRequest reviewer username
    default: TorinAsakura
    required: true
  lastPrAuthor:
    description: PullRequest reviewer username
    default: TorinAsakura
    required: true
  commitMessage:
    default: 'feat: automated commit'
    description: commit message
    required: false
  branchName:
    description: git branch name
    required: true
  targetRepository:
    description: pull reques target repository
    required: false

runs:
  using: composite

  steps:
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        path: ${{ inputs.targetDirectory || '.' }}
        branch: ${{ inputs.branchName }}
        commit-message: ${{ inputs.commitMessage }}
        sign-commits: true
        delete-branch: true
        draft: false
        token: ${{ inputs.githubToken }}
        title: ${{ inputs.prTitle }}
        body: ${{ inputs.prBody }}
        base: ${{ github.ref }}
        assignees: ${{ inputs.lastPrAuthor || inputs.reviewerUsername }}
        reviewers: ${{ inputs.reviewerUsername }}

    - name: Enable Pull Request Automerge
      shell: bash
      run: gh pr merge --squash --admin "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
