name: Create pull request on target repo
description: create pull request on target repo

inputs:
  targetDirectory:
    default: tmp/target
    description: Commit author GitHub token
    required: true
  githubToken:
    description: GitHub token
    required: true
  prTitle:
    description: PullRequest title
    default: Automated release
    required: false
  prBody:
    description: PullRequest body
    default: This is an automated pull request
    required: false
  reviewerUsername:
    description: PullRequest reviewer username
    default: nelfimov
    required: true
  lastPrAuthor:
    description: PullRequest reviewer username
    default: TorinAsakura
    required: true
  commitMessage:
    default: 'feat: automated commit'
    description: commit message
    required: false
  branchName:
    description: git branch name
    required: true
  targetRepository:
    description: pull request target repository
    required: false

runs:
  using: composite

  steps:
    - id: changed-files
      uses: tj-actions/changed-files@v46.0.5

    - name: List all changed files
      shell: bash
      env:
        ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      run: |
        for file in ${ALL_CHANGED_FILES}; do
          echo "$file was changed"
        done
        sudo chmod -R ugo+rwX .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      id: cpr
      with:
        path: ${{ inputs.targetDirectory || '.' }}
        branch: ${{ inputs.branchName }}
        commit-message: ${{ inputs.commitMessage }}
        sign-commits: true
        delete-branch: true
        draft: false
        token: ${{ inputs.githubToken }}
        title: ${{ inputs.prTitle }}
        body: ${{ inputs.prBody }}
        base: ${{ github.ref }}
        assignees: ${{ inputs.lastPrAuthor || inputs.reviewerUsername }}
        reviewers: ${{ inputs.reviewerUsername }}

    - name: Enable Pull Request Automerge
      shell: bash
      run: gh pr merge --squash --admin "${{ steps.cpr.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
