name: Get last merget PullRequest author
description: get last merget pull request author

inputs:
  sourceDirectory:
    default: tmp/source
    description: Commit author GitGup token
    required: true
  githubToken:
    description: GitHup token
    required: true
  reviewerUsername:
    description: github pull request reviewer username
    required: true

outputs:
  lastPrAuthor:
    description: Get branch name
    value: ${{ steps.pr_author.outputs.lastPrAuthor }}

runs:
  using: composite

  steps:
    - name: Get last merged PR author login
      shell: bash
      working-directory: ${{ inputs.sourceDirectory }}
      id: pr_author
      env:
        GH_TOKEN: ${{ inputs.githubToken }}
      run: |
        ASSIGNEE=$(gh pr list --state merged --limit 1 \
          --json assignees --jq '.[0].assignees[0].login // ""')

        if [ -z "$ASSIGNEE" ]; then
          ASSIGNEE=${{ inputs.reviewerUsername }}
        fi

        echo "assignee=$ASSIGNEE" >> $GITHUB_OUTPUT
