name: Build actions

on:
  pull_request:
    branches:
      - master
    types:
      - closed

jobs:
  run:
    name: Build
    uses: rees46/workflow/.github/workflows/reusable-build.yaml@master
    permissions: write-all
    with:
      appId: ${{ vars.PUBLIVERSIONER_ID }}
    secrets:
      appSecret: ${{ secrets.PUBLIVERSIONER_SECRET }}
