name: Repository synchronization

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  prepare:
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    outputs:
      replacements: ${{ steps.getReplacementsStep.outputs.replacements }}
    steps:
      - uses: rees46/workflow/.github/actions/sync/read-replacements@master
        id: getReplacementsStep
        with:
          appId: ${{ vars.VERSIONER_ID }}
          appSecret: ${{ secrets.VERSIONER_SECRET }}
          replacementsPath: github/repo-sync-replacements/workflow.yml

  repoSync:
    needs: prepare
    uses: rees46/workflow/.github/workflows/reusable-repo-sync.yml@master
    secrets:
      appSecret: ${{ secrets.PERSONACLICK_COURIER_SECRET }}
    with:
      appId: ${{ vars.PERSONACLICK_COURIER_ID }}
      replacements: ${{ needs.prepare.outputs.replacements }}
      repositoryOwner: personaclick
      targetRepository: personaclick/workflow
      reviewerUsername: nelfimov
