name: iOS checks

on:
  workflow_call:
    secrets:
      cocoapodsToken:
        description: Cocoapods token
        required: true

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v --parallel

      - name: Lint
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod spec lint --allow-warnings
