name: iOS checks

on:
  workflow_call:
    inputs:
      googleServicesFileLocation:
        required: false
        type: string
        default: './DemoApp/REES46Demo/Supporting Files/'
      googleServicesFileName:
        required: false
        type: string
        default: GoogleService-Info.plist

    secrets:
      googleServicesString:
        description: Google services file as base64 string
        required: true
      cocoapodsToken:
        description: Cocoapods token
        required: true
      testShopId:
        required: false
      testApiUrl:
        required: false

jobs:
  run:
    runs-on: macos-latest
    env:
      ACTIONS_IS_RUNNING: true
      TEST_SHOP_ID: ${{ secrets.testShopId }}
      TEST_API_URL: ${{ secrets.testApiUrl }}
    steps:
      - run: env

      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-deriveddata-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-deriveddata-

      - uses: actions/cache@v4
        with:
          path: Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Pod install
        working-directory: ./DemoApp
        run: |
          pod install

      - name: Decode signing key file
        uses: timheuer/base64-to-file@v1.2
        id: service_account_json_file
        with:
          fileName: ${{ inputs.googleServicesFileName }}
          fileDir: ${{ inputs.googleServicesFileLocation }}
          encodedString: ${{ secrets.googleServicesString }}

      - name: Copy Google Service
        run: |
          cp ./DemoApp/REES46Demo/Supporting\ Files/GoogleService-Info.plist ./DemoApp/GoogleService-Info.plist
          cp ./DemoApp/REES46Demo/Supporting\ Files/GoogleService-Info.plist ./DemoApp/REES46.xcodeproj/xcshareddata/xcschemes/GoogleService-Info.plist
          cp ./DemoApp/REES46Demo/Supporting\ Files/GoogleService-Info.plist ./DemoApp/REES46Demo/GoogleService-Info.plist

      - name: Build
        run: |
          xcodebuild build -workspace ./DemoApp/REES46.xcworkspace -scheme REES46Demo \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS=''

      - name: Run tests
        if: ${{ !cancelled() }}
        run: |
          xcodebuild test -workspace ./DemoApp/REES46.xcworkspace -scheme REES46Demo \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS=''

      - name: Lint spec
        if: ${{ !cancelled() }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod spec lint --allow-warnings

      - name: Lint lib
        if: ${{ !cancelled() }}
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod lib lint --allow-warnings
