name: Reusable version bump

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: App token for committing changes
      reviewerUsername:
        required: false
        type: string
        description: Pull request reviewer
        default: TorinAsakura

    secrets:
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0
          ref: master

      - uses: codfish/semantic-release-action@v3
        id: semanticReleaseStep
        with:
          additional-packages: |
            ['@semantic-release/git', '@semantic-release/exec']

      - name: Check release published
        shell: bash
        run: |
          if [ "${NEW_RELEASE_PUBLISHED}" != "true" ]; then
            echo "New release not published, exit"
            exit 1
          fi

      - uses: rees46/workflow/.github/actions/git/create-relese-branch@master
        id: createReleaseBranchStep
        with:
          githubToken: ${{ steps.app-token.outputs.token }}
          releaseVersion: ${{ steps.semanticReleaseStep.outputs.release-version }}

      - uses: rees46/workflow/.github/actions/github/pull-request/get-last-author@master
        id: lastPrAuthorStep
        with:
          sourceDirectory: .
          githubToken: ${{ steps.app-token.outputs.token }}

      - uses: rees46/workflow/.github/actions/github/commit/create@master
        with:
          branchName: ${{ steps.createReleaseBranchStep.outputs.branchName }}
          githubToken: ${{ steps.app-token.outputs.token }}
          targetRepository: ${{ github.repository }}
          filePattern: version.properties

      - uses: rees46/workflow/.github/actions/github/pull-request/create@master
        with:
          targetDirectory: .
          githubToken: ${{ steps.app-token.outputs.token }}
          lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
          prTitle: "Bump version to ${{ steps.semanticReleaseStep.outputs.release-version }}"
          prBody: "Automated version bump"
          branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
          reviewerUsername: ${{ inputs.reviewerUsername }}
