name: Reusable Android SDK publish to Sona

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: 'App ID for committing and pushing'
      PROPERTIES_FILE:
        default: gradle.properties
        type: string
        description: Relative file path for putting in secrets
        required: false
      SIGNING_SECRET_KEY_RING_FILE:
        default: com.rees46.key.gpg
        type: string
        description: Location and name for signature file
        required: false
      SIGNING_SECRET_KEY_RING_FILE_LOCATION:
        type: string
        description: Location and name for signature file
        required: false
        default: ./personalization-sdk
      GRADLE_VERSION:
        type: number
        required: false
      VARIANT_NAME:
        description: REES46 or PersonaClick
        type: string
        required: true
      URL:
        description: GitHub repo URL
        type: string
        required: true
      MAVEN_REPOSITORY_URL:
        description: Maven repository publish to
        type: string
        required: true
      OSSRH_USERNAME:
        required: false
        type: string
        default: 'github-bot@rees46.com'
    secrets:
      appSecret:
        required: true
      SONATA_USERNAME:
        required: true
      SONATA_STAGING_PROFILE_ID:
        required: true
      SONATA_PASSWORD:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SIGNING_KEY_FILE_AS_BASE64_STRING:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: master
          fetch-depth: 0

      - name: Prepare Android Action
        uses: rees46/workflow/.github/actions/android/prepare@master
        with:
          PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_SECRET_KEY_RING_FILE_LOCATION: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE_LOCATION }}
          VARIANT_NAME: ${{ inputs.VARIANT_NAME }}
          URL: ${{ inputs.URL }}
          MAVEN_REPOSITORY_URL: ${{ inputs.MAVEN_REPOSITORY_URL }}
          OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATA_USERNAME: ${{ secrets.SONATA_USERNAME }}
          SONATA_PASSWORD: ${{ secrets.SONATA_PASSWORD }}
          SONATA_STAGING_PROFILE_ID: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}

      - name: Publish
        run: |
          ./gradlew publish

      - name: Install xmllint
        run: |
          sudo apt-get update
          sudo apt-get install -y libxml2-utils

      - name: Debug profile id
        run: |
          echo ${{ secrets.SONATA_STAGING_PROFILE_ID }}

      - name: Get repos.xml
        id: get_repos
        run: |
          REPOS=$(curl -s -u ${{ secrets.SONATA_USERNAME }}:${{ secrets.SONATA_PASSWORD }} https://s01.oss.sonatype.org/service/local/staging/profile_repositories/${{ secrets.SONATA_STAGING_PROFILE_ID }})
          echo "REPOS: $REPOS"
          echo "$REPOS" > repos.xml

      - name: Extract repository IDs
        id: extract_ids
        run: |
          repository_ids=($(xmllint --xpath '//repositoryId/text()' repos.xml))
          echo "Repository IDs: ${repository_ids[@]}"
          echo "repository_ids=${repository_ids[*]}" >> $GITHUB_OUTPUT

      - name: Close stages
        run: |
          IFS=' ' read -r -a ids_array <<< "${{ steps.extract_ids.outputs.repository_ids }}"

          for id in "${ids_array[@]}"; do
            curl -X POST \
              -u "${{ secrets.SONATA_USERNAME }}":"${{ secrets.SONATA_PASSWORD }}" \
              -H "Content-Type: application/json" \
              -d '{
                "data": {
                  "stagedRepositoryId": '$id'
                }
              }' \
              "https://s01.oss.sonatype.org/service/local/staging/profiles/${{ secrets.SONATA_STAGING_PROFILE_ID }}/finish"
          done

      - name: Sleep 5 minutes
        run: |
          sleep 300

      - name: Release stages
        run: |
          IFS=' ' read -r -a ids_array <<< "${{ steps.extract_ids.outputs.repository_ids }}"

          for id in "${ids_array[@]}"; do
            curl -X POST \
              -u "${{ secrets.SONATA_USERNAME }}":"${{ secrets.SONATA_PASSWORD }}" \
              -H "Content-Type: application/json" \
              -d '{
                "data": {
                  "stagedRepositoryId": '$id'
                }
              }' \
              "https://s01.oss.sonatype.org/service/local/staging/profiles/${{ secrets.SONATA_STAGING_PROFILE_ID }}/promote"
          done
