name: Reusable version

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 18.19 as it is in action cache'
        default: '18.19'
        required: false
        type: string

jobs:
  run:
    name: Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: yarn install --mode=update-lockfile --inline-builds
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Find Base Commit for master
        id: find_base_commit
        run: |
          echo "Finding base commit between HEAD and origin/master"
          base_commit=$(git log --merges -n 2 --format=format:%H | tail -n 1)
          echo "::set-output name=base_commit::$base_commit"
          echo "Base Commit: $base_commit"

      - name: Version
        run: yarn workspaces foreach --since=${{ steps.find_base_commit.outputs.base_commit }} --no-private --verbose version patch --deferred
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: GitSign
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit changes
        if: ${{ !env.ACT }}
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: -S
          default_author: github_actions
          author_email: github-bot@rees46.com
          message: 'chore(common): version'
          add: '*.yml'
