name: Reusable infrastructure checks ansible

on:
  workflow_call:
    inputs:
      ANSIBLE_PATH:
        required: false
        default: ansible
        type: string
    secrets:
      SVC_CICD_PRIVATE_KEY:
        required: true

jobs:
  lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      working_directory: ${{ inputs.ANSIBLE_PATH }}
