name: iOS publish Swift pacakge and Cocoapods

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: App token for committing changes

    secrets:
      cocoapodsToken:
        description: Cocoapods token
        required: true
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: master

      - uses: swift-actions/setup-swift@v2

      - name: Publish to cocoapods.org
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: |
          retry=0
          max_retries=5
          while [ $retry -lt $max_retries ]; do
            pod trunk push --allow-warnings && break
            retry=$((retry+1))
            echo "Push failed. Retrying in 30 seconds... ($retry/$max_retries)"
            sleep 30
          done
