name: Reusable Android SDK release

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: 'App ID for committing and pushing'
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: master
          fetch-depth: 0

      - name: Retrieve version
        id: versionName
        env:
          FILE_PATH: ./personalization-sdk/build.gradle
        run: |
          version=$(grep -o "version='[^']*'" $FILE_PATH | head -1 | cut -d"'" -f2)
          echo "versionName=$version" >> $GITHUB_ENV
          echo "versionName=$version" >> $GITHUB_OUTPUT

      - name: Zip source
        run: |
          tar -czvf source.tgz *

      - name: Create release
        env:
          TAG: ${{ steps.versionName.outputs.versionName }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          gh release create "v$TAG" ./source.tgz \
          --title=$TAG \
          --generate-notes
