name: Enforce merge source rule

on:
  workflow_call:
    inputs:
      allowedBranch:
        description: 'Which branch is allowed to be merged from'
        type: string
        required: true
        default: 'stage'
      allowedTarget:
        description: 'Which target branch is allowed'
        type: string
        required: false
        default: 'master'

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from allowed branches
        run: |
          echo "Source branch: $GITHUB_HEAD_REF"
          echo "Target branch: $GITHUB_BASE_REF"
          if [[ "$GITHUB_BASE_REF" == "$ALLOWED_BASE_BRANCH" ]]; then
            if [[ ! "$GITHUB_HEAD_REF" == "$ALLOWED_HEAD_BRANCH" ]]; then
              echo "Merging to '$ALLOWED_BASE_BRANCH' is only allowed from '$ALLOWED_HEAD_BRANCH' branch"
              exit 1
            fi
          fi
        env:
          GITHUB_HEAD_REF: ${{ github.head_ref }}
          GITHUB_BASE_REF: ${{ github.base_ref }}
          ALLOWED_HEAD_BRANCH: ${{ inputs.allowedBranch }}
          ALLOWED_BASE_BRANCH: ${{ inputs.allowedTarget }}
