name: Reusable multiplatform bump

env:
  WORKFLOW_REPO: "rees46/workflow"
  PROPERTIES_FILE: "version.properties"

on:
  workflow_call:
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_PRIVATE_KEY:
        required: true

jobs:
  publish_and_version_bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.GITHUB_APP_ID }}
          private-key: ${{ secrets.GITHUB_APP_PRIVATE_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Checkout Workflow Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WORKFLOW_REPO }}
          path: workflow
          sparse-checkout: |
            scripts/multiplatform

      - name: Increment vesion manually
        run: |
          ./workflow/scripts/multiplatform/increment-patch-version.sh
          VERSION=$(./workflow/scripts/multiplatform/get-version-code.sh)

      # Retrieve new version
      - name: Retrieve new version
        id: versionName
        run: |
          version=$(./workflow/scripts/multiplatform/get-version-name.sh)
          echo "versionName=$version" >> $GITHUB_ENV
          echo "versionName=$version" >> $GITHUB_OUTPUT

      # Commit version changes
      - name: Commit version changes
        id: committer
        uses: planetscale/ghcommit-action@v0.1.6
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: "chore: bump version to ${{ steps.versionName.outputs.versionName }}"
          file_pattern: ${{ env.PROPERTIES_FILE }}
