name: iOS publish Swift pacakge and Cocoapods

on:
  workflow_call:
    inputs:
      podSpecFilePath:
        default: 'REES46.podspec'
        type: string
        required: false
        description: File path to podspec file
      appId:
        required: true
        type: string
        description: App token for committing changes
    secrets:
      cocoapodsToken:
        description: Cocoapods token
        required: true
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - uses: swift-actions/setup-swift@v2

      - name: Bump version
        env:
          FILE_PATH: ${{ inputs.podSpecFilePath }}
        id: version
        run: |
          current_version=$(awk -F"'" '/s.version *=/ {print $2}' "$FILE_PATH")
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i '' "s/$current_version/$new_version/" "$FILE_PATH"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          VERSION: ${{ steps.version.outputs.version }}
        run: gh release create "$VERSION" --title=$VERSION --generate-notes

      - name: Commit changes
        id: committer
        uses: EndBug/add-and-commit@v9
        env:
          VERSION: ${{ steps.version.outputs.version }}
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          default_author: github_actions
          author_email: github-bot@rees46.com
          message: "chore(common): version bump to $VERSION"
          add: '["*.podspec"]'

      - name: Publish to cocoapods.org
        if: steps.committer.outputs.committed == 'true'
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod trunk push --allow-warnings
