name: Reusable infrastructure checks k8s

on:
  workflow_call:
    inputs:
      PATH:
        type: string
        default: specs
        required: true

jobs:
  check:
    name: Check Kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Kube Linter Action
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ${{ inputs.PATH }}

      - uses: docker://ghcr.io/yannh/kubeconform:latest
        if: ${{ !cancelled() }}
        with:
          entrypoint: '/kubeconform'
          args: '-summary -output pretty ${{ inputs.PATH }}'
