name: Reusable JS/TS version bump & create PR

on:
  workflow_call:
    inputs:
      appId:
        description: GitHub app id
        required: true
        type: string
      node-version:
        description: 'Node version to run this workflow. Default: 19 as it is in action cache'
        default: '22'
        required: false
        type: string
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false
      exclude:
        required: false
        description: Which workspaces to exclude
        type: string
        default: 'nothing'
    secrets:
      appSecret:
        required: true
      npmToken:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Start JS action
        id: start
        uses: rees46/workflow/.github/actions/js/start-js@master
        with:
          appId: ${{ inputs.appId }}
          appSecret: ${{ secrets.appSecret }}

      - name: Find last tag commit
        id: lastTagCommit
        uses: rees46/workflow/.github/actions/git/find-last-tag-commit@master

      - name: Publish to npm registry
        if: ${{ !contains(github.event.pull_request.title, 'revert') && !contains(github.event.pull_request.title, 'chore') && !cancelled() }}
        uses: rees46/workflow/.github/actions/js/publish-to-registry@master
        with:
          baseCommit: ${{ steps.lastTagCommit.outputs.lastTagCommit }}
          token: ${{ steps.start.outputs.token }}
          npmAuthToken: ${{ secrets.npmToken }}
          exclude: ${{ inputs.exclude }}
