name: Reusable Ruby publish migrated DB

on:
  workflow_call:
    inputs:
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false
      rubyVersion:
        description: Ruby version to use
        default: '2.7.5'
        type: string
        required: false
      nodeVersion:
        description: Node version to use
        default: '20'
        type: string
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

    steps:
      - name: PSQL client
        run: sudo apt-get install --yes --no-install-recommends postgresql-client

      - name: Start postgres
        env:
          PGPASSWORD: postgres
          PGUSER: postgres
          PGHOST: localhost
        run: |
          psql -c "CREATE USER rails WITH SUPERUSER PASSWORD 'rails';"
          psql -c "CREATE USER rees46 WITH SUPERUSER PASSWORD 'rees46';"
#          psql -c "CREATE DATABASE rees46_test WITH OWNER rees46;"
#          psql -c "CREATE DATABASE rees46_clickhouse_rails_test WITH OWNER rees46;"
#          psql -c "CREATE DATABASE rees46_rails_test WITH OWNER rees46;"
#          psql -c "CREATE DATABASE rees46_clickhouse_test WITH OWNER rees46;"
#          psql -d rees46 -c "SELECT version();"
#          psql -c "CREATE DATABASE rees46_production WITH OWNER rees46;"
#          psql -c "CREATE DATABASE rees46_clickhouse WITH OWNER rees46;"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Start clickhouse server
        run: |
          docker run -d \
          --name clickhouse_server \
          -e CLICKHOUSE_USER='rees46' \
          -e CLICKHOUSE_PASSWORD='rees46' \
          -e CLICKHOUSE_DB='rees46_clickhouse_test' \
          -p 8123:8123 \
          -p 9000:9000 \
          -p 9009:9009 \
          -p 9004:9004 \
          -p 9005:9005 \
          --ulimit nofile=262144:262144 \
          yandex/clickhouse-server:22-alpine;
          docker cp ./config/clickhouse-config.xml clickhouse_server:/etc/clickhouse-server/config.xml

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.nodeVersion }}

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.rubyVersion }}
          bundler-cache: true

      - name: Yarn install
        run: yarn install --inline-builds

      - name: Prepare configs
        run: |
          mv ./config/database.yml.example ./config/database.yml
          mv ./config/secrets.yml.example ./config/secrets.yml

      - name: Change configs
        run: |
          file="./config/database.yml"
          sed -i -e '/^test_clickhouse:/!b' -e 'n' -e 's/.*/  <<: *default_clickhouse/' "$file"

      - name: Run migrations
        env:
          PG_PASSWORD: rees46
          PG_USER: rees46
          RAILS_ENV: test
        run: |
          bundle exec rake db:create
          bundle exec rake db:schema:load 
          bundle exec rake clickhouse:create 
          bundle exec rake clickhouse:schema:load 
          bundle exec rake clickhouse:schema:load -- --simple

      - name: Publish postgres docker image
        run: |
          docker commit postgres ghcr.io/rees46/postgres-migrated:latest
          docker push ghcr.io/rees46/postgres-migrated:latest

      - name: Publish clickhouse server docker image
        run: |
          docker commit clickhouse_server ghcr.io/rees46/clickhouse-server-migrated:latest
          docker push ghcr.io/rees46/clickhouse-server-migrated:latest
