name: Reusable repository synchronization

env:
  WORKFLOW_REPO: "rees46/workflow"
  WORKFLOW_TMP_PATH: tmp/workflow/
  TARGET_TMP_PATH: tmp/target/
  SOURCE_TMP_PATH: tmp/source/
#
on:
  workflow_call:
    secrets:
      appSecret:
        description: App secret for committing changes
        required: true
    inputs:
      appId:
        description: App ID for committing and pushing
        required: true
        type: string
      replacements:
        description: Replacements
        required: true
        type: string
      targetRepository:
        description: Target repository to sync
        required: true
        type: string
      repositoryOwner:
        type: string
        required: true

jobs:
  prepareSync:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      # - uses: rees46/workflow/.github/actions/sync/prepare@master
      - uses: rees46/workflow/.github/actions/sync/prepare@refactor/ios-sync-workflow
        with:
          appId: ${{ inputs.appId }}
          appSecret: ${{ secrets.appSecret }}
          repositoryOwner: ${{ inputs.repositoryOwner }}
          targetRepository: ${{ inputs.targetRepository }}

      # Process
      - name: Clean target directory
        working-directory: ${{ env.WORKFLOW_TMP_PATH }}
        run: |
          TARGET_TMP_ABS_PATH="$GITHUB_WORKSPACE/${{ env.TARGET_TMP_PATH }}"
          yarn workspace @scripts/clean-directory process '${{ inputs.replacements }}' "$TARGET_TMP_ABS_PATH"

      - name: Debug tmp absolute
        run: |
          ABSOLUTE_PATH="$GITHUB_WORKSPACE/$TARGET_TMP_PATH"
          cd "$ABSOLUTE_PATH" && ls -a

      # - uses: rees46/workflow/.github/actions/utils/fs/sync-dirs@master
      - uses: rees46/workflow/.github/actions/utils/fs/sync-dirs@refactor/ios-sync-workflow
        with:
          targetDirectory: ${{ env.TARGET_TMP_PATH }}
          sourceDirectory: ${{ env.SOURCE_TMP_PATH }}

      - name: Process replacements
        working-directory: tmp/workflow
        run: |
          # TODO to prepare sync
          ABSOLUTE_PATH="$GITHUB_WORKSPACE/${{ env.TARGET_TMP_PATH }}"
          yarn workspace @scripts/repo-replacement process '${{ inputs.replacements }}' "$ABSOLUTE_PATH"

      - name: Debug
        working-directory: ${{ env.TARGET_TMP_PATH }}
        run: git status

      - name: Debug
        working-directory: ${{ env.TARGET_TMP_PATH }}
        run: git diff

      # Prepare pull request
      # # TODO prepare pull-request action
      # - uses: rees46/workflow/.github/actions/github/pull-request/get-last-author@master
      #   id: lastPrAuthorStep
      #   with:
      #     sourceDirectory: ${{ env.SOURCE_TMP_PATH }}
      #     githubToken: ${{ steps.appTokenStep.outputs.token }}
      #
      # - uses: rees46/workflow/.github/actions/github/utils/get-new-branch-name@master
      #   id: newBranchNameStep
      #
      # # - uses: rees46/workflow/.github/actions/git/checkout-new-branch@master
      # - uses: rees46/workflow/.github/actions/git/checkout-new-branch@refactor/ios-sync-workflow
      #   with:
      #     workingDirectory: ${{ env.TARGET_TMP_PATH }}
      #     branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
      #
      # # - uses: rees46/workflow/.github/actions/git/add@master
      # - uses: rees46/workflow/.github/actions/git/add@refactor/ios-sync-workflow
      #   with:
      #     workingDirectory: ${{ env.TARGET_TMP_PATH }}
      #     excludeTmp: true
      #
      # # - uses: rees46/workflow/.github/actions/github/commit/create@master
      # - uses: rees46/workflow/.github/actions/github/commit/create@refactor/ios-sync-workflow
      #   with:
      #     workingDirectory: ${{ env.TARGET_TMP_PATH }}
      #     branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
      #     githubToken: ${{ steps.appTokenStep.outputs.token }}
      #     targetRepository: ${{ inputs.targetRepository }}
      #
      # # - uses: rees46/workflow/.github/actions/github/pull-request/create@master
      # - uses: rees46/workflow/.github/actions/github/pull-request/create@refactor/ios-sync-workflow
      #   with:
      #     # TODO pass from upper
      #     # reviewerUsername: ${{ inputs.reviewerUsername }}
      #     reviewerUsername: iwwwanow
      #     targetDirectory: ${{ env.TARGET_TMP_PATH }}
      #     githubToken: ${{ steps.appTokenStep.outputs.token }}
      #     lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
      #     branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
