# action uses codfish/semantic-release-action and for correct work needs .releaserc.yml in project root with @semantic-release/exec + prepareCmd on config for correct bump work.

name: Reusable version bump

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: App token for committing changes
      reviewerUsername:
        required: false
        type: string
        description: Pull request reviewer
        default: TorinAsakura

    secrets:
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - uses: codfish/semantic-release-action@v3
        id: semanticReleaseStep
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          additional-packages: |
            ['@semantic-release/git', '@semantic-release/exec']

      - name: Debug git diff
        run: |
          git diff

      - name: Check release published
        shell: bash
        run: |
          if [ "${NEW_RELEASE_PUBLISHED}" != "true" ]; then
            echo "New release not published, exit"
            exit 1
          fi

      - uses: rees46/workflow/.github/actions/release/prepare-pr@master
        with:
          reviewerUsername: ${{ inputs.reviewerUsername }}
          githubToken: ${{ steps.app-token.outputs.token }}
          releaseVersion: ${{ steps.semanticReleaseStep.outputs.release-version }}
