name: Reusable Android SDK publish to Sona

on:
  workflow_call:
    inputs:
      PROPERTIES_FILE:
        default: gradle.properties
        type: string
        description: Relative file path for putting in secrets
        required: false
      SIGNING_SECRET_KEY_RING_FILE:
        default: com.rees46.key.gpg
        type: string
        description: Location and name for signature file
        required: false
      SIGNING_SECRET_KEY_RING_FILE_LOCATION:
        type: string
        description: Location and name for signature file
        required: true
        default: ./personalization-sdk
      GOOGLE_SERVICES_FILE_LOCATION:
        default: sample
        type: string
        description: Location for google services file
        required: false
      GOOGLE_SERVICES_FILE_NAME:
        default: google-services.json
        type: string
        description: Name for google services file
        required: false
      GRADLE_VERSION:
        type: number
        required: false
      VARIANT_NAME:
        description: REES46 or PersonaClick
        type: string
        required: true
      URL:
        description: GitHub repo URL
        type: string
        required: true
      MAVEN_REPOSITORY_URL:
        description: Maven repository publish to
        type: string
        required: true
      OSSRH_USERNAME:
        required: false
        type: string
        default: 'github-bot@rees46.com'
    secrets:
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SIGNING_KEY_FILE_AS_BASE64_STRING:
        required: true
      GOOGLE_SERVICES_FILE_AS_BASE64_STRING:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare Android Action
        uses: rees46/workflow/.github/actions/android/prepare@master
        with:
          GRADLE_VERSION: ${{ inputs.GRADLE_VERSION }}
          PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_SECRET_KEY_RING_FILE_LOCATION: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE_LOCATION }}
          VARIANT_NAME: ${{ inputs.VARIANT_NAME }}
          URL: ${{ inputs.URL }}
          MAVEN_REPOSITORY_URL: ${{ inputs.MAVEN_REPOSITORY_URL }}
          OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}

      - name: Decode google services key file
        uses: timheuer/base64-to-file@v1.2
        id: google_services_json_file
        with:
          fileName: ${{ inputs.GOOGLE_SERVICES_FILE_NAME }}
          fileDir: ${{ inputs.GOOGLE_SERVICES_FILE_LOCATION }}
          encodedString: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64_STRING }}

      - name: Create keystore
        run: |
          keytool -genkey -dname "cn=Unknown, ou=unknown, o=unknown, l=unknown, st=unknown, c=unknown" \
          -keystore ./test.key -storepass 123456 -keypass 123456 -alias test -keyalg RSA -keysize 4096 -validity 10000 -v

      - name: Test
        if: ${{ !cancelled() }}
        run: ./gradlew test

      - name: Lint
        if: ${{ !cancelled() }}
        run: ./gradlew lint

      - name: Check
        if: ${{ !cancelled() }}
        run: ./gradlew check

      - name: Build
        if: ${{ !cancelled() }}
        run: ./gradlew build
