name: iOS create release

on:
  workflow_call:
    inputs:
      podSpecFilePath:
        default: 'REES46.podspec'
        type: string
        required: false
        description: File path to podspec file
      appId:
        required: true
        type: string
        description: App token for committing changes

    secrets:
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: master

      - name: Retrieve version
        env:
          FILE_PATH: ${{ inputs.podSpecFilePath }}
        id: version
        run: |
          current_version=$(awk -F"'" '/s.version *=/ {print $2}' "$FILE_PATH")
          echo "version=$current_version" >> $GITHUB_OUTPUT

      - name: Create release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          VERSION: ${{ steps.version.outputs.version }}
        run: gh release create "$VERSION" --title=$VERSION --generate-notes
