name: Reusable Android SDK publish to Sona

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: "App ID for committing and pushing"
      PROPERTIES_FILE:
        default: gradle.properties
        type: string
        description: Relative file path for putting in secrets
        required: false
      SIGNING_SECRET_KEY_RING_FILE:
        default: com.rees46.key.gpg
        type: string
        description: Location and name for signature file
        required: false
      SIGNING_SECRET_KEY_RING_FILE_LOCATION:
        type: string
        description: Location and name for signature file
        required: false
        default: ./personalization-sdk
      GRADLE_VERSION:
        type: number
        required: false
      VARIANT_NAME:
        description: REES46 or PersonaClick
        type: string
        required: true
      URL:
        description: GitHub repo URL
        type: string
        required: true
      MAVEN_REPOSITORY_URL:
        description: Maven repository publish to
        type: string
        required: true
      OSSRH_USERNAME:
        required: false
        type: string
        default: "github-bot@rees46.com"
    secrets:
      appSecret:
        required: true
      SONATA_USERNAME:
        required: true
      SONATA_STAGING_PROFILE_ID:
        required: true
      SONATA_PASSWORD:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SIGNING_KEY_FILE_AS_BASE64_STRING:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          # ref: master
          # TODO remove
          ref: fix/publish-android
          fetch-depth: 0

      - name: Prepare Android Action
        uses: rees46/workflow/.github/actions/android/prepare@master
        with:
          PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE }}
          SIGNING_SECRET_KEY_RING_FILE_LOCATION: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE_LOCATION }}
          VARIANT_NAME: ${{ inputs.VARIANT_NAME }}
          URL: ${{ inputs.URL }}
          MAVEN_REPOSITORY_URL: ${{ inputs.MAVEN_REPOSITORY_URL }}
          OSSRH_USERNAME: ${{ inputs.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SONATA_USERNAME: ${{ secrets.SONATA_USERNAME }}
          SONATA_PASSWORD: ${{ secrets.SONATA_PASSWORD }}
          SONATA_STAGING_PROFILE_ID: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY_FILE_AS_BASE64_STRING: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}

      - name: Create staging repository
        uses: nexus-actions/create-nexus-staging-repo@990063f02160c633c168037b8b3e8585c76469fe
        id: createStagingRepoStep
        with:
          username: ${{ secrets.SONATA_USERNAME }}
          password: ${{ secrets.SONATA_PASSWORD }}
          staging_profile_id: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
          base_url: "https://s01.oss.sonatype.org/service/local/"
          # base_url: "https://s01.oss.sonatype.org/service/local/staging/deploy/maven2/"

      - name: Debug repo id
        run: |
          echo "${{ steps.createStagingRepoStep.outputs.repository_id }}"

      - name: Clean gradlew cache
        run: |
          ./gradlew clean

      - name: Publish
        env:
          SONATYPE_REPOSITORY_ID: ${{ steps.createStagingRepoStep.outputs.repository_id }}
        run: |
          # ./gradlew publish -Psonatype
          # TODO rm
          ./gradlew publishAllPublicationsToSonatypeRepository -Psonatype

      # - name: Install xmllint
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y libxml2-utils

      # - name: Debug profile id
      #   run: |
      #     echo ${{ secrets.SONATA_STAGING_PROFILE_ID }}

      - name: Release
        uses: nexus-actions/release-nexus-staging-repo@6632a81bfab63557b2717e8423b0a620ae5aa414
        with:
          username: ${{ secrets.SONATA_USERNAME }}
          password: ${{ secrets.SONATA_PASSWORD }}
          staging_repository_id: ${{ steps.createStagingRepoStep.outputs.repository_id }}
          base_url: "https://s01.oss.sonatype.org/service/local/"

      # - name: Get repository ids
      #   id: getRepoIdsStep
      #   run: |
      #     response=$(curl -s \
      #       -u "${{ secrets.SONATA_USERNAME }}":"${{ secrets.SONATA_PASSWORD }}" \
      #       -H "Accept: application/json" \
      #       "https://s01.oss.sonatype.org/service/local/staging/profile_repositories/${{ secrets.SONATA_STAGING_PROFILE_ID }}")
      #
      #     response_json=$(echo "$response_body" | jq .)
      #     echo "$response_json"
      #
      # - name: Extract repository IDs
      #   id: extract_ids
      #   run: |
      #     repository_ids=($(xmllint --xpath '//repositoryId/text()' repos.xml))
      #     echo "Repository IDs: ${repository_ids[@]}"
      #     echo "repository_ids=${repository_ids[*]}" >> $GITHUB_OUTPUT
      #
      # - name: Close stages
      #   uses: rees46/workflow/.github/actions/sonatype/request@master
      #   with:
      #     requestEndpoint: finish
      #     repositoryIds: ${{ steps.extract_ids.outputs.repository_ids }}
      #     sonataUsername: ${{ secrets.SONATA_USERNAME }}
      #     sonataPassword: ${{ secrets.SONATA_PASSWORD }}
      #     sonataStagingProfileId: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
      #
      # - name: Sleep 2 minutes
      #   run: |
      #     sleep 120
      #
      # - name: Check sonatype repositories
      #   uses: rees46/workflow/.github/actions/sonatype/check-repos@master
      #   with:
      #     repositoryIds: ${{ steps.extract_ids.outputs.repository_ids }}
      #     sonataUsername: ${{ secrets.SONATA_USERNAME }}
      #     sonataPassword: ${{ secrets.SONATA_PASSWORD }}
      #
      # - name: Release stages
      #   uses: rees46/workflow/.github/actions/sonatype/request@master
      #   with:
      #     requestEndpoint: promote
      #     repositoryIds: ${{ steps.extract_ids.outputs.repository_ids }}
      #     sonataUsername: ${{ secrets.SONATA_USERNAME }}
      #     sonataPassword: ${{ secrets.SONATA_PASSWORD }}
      #     sonataStagingProfileId: ${{ secrets.SONATA_STAGING_PROFILE_ID }}
      #
      # - name: Sleep 2 minutes
      #   run: |
      #     sleep 120
      #
      # - name: Check sonatype repositories
      #   uses: rees46/workflow/.github/actions/sonatype/check-repos@master
      #   with:
      #     repositoryIds: ${{ steps.extract_ids.outputs.repository_ids }}
      #     sonataUsername: ${{ secrets.SONATA_USERNAME }}
      #     sonataPassword: ${{ secrets.SONATA_PASSWORD }}
