name: Build & Publish Android

on:
  workflow_call:
    secrets:
      PLAY_ACCOUNT_AS_BASE64:
        required: true
      KEYSTORE_AS_BASE64:
        required: true
      GOOGLE_SERVICES_FILE_AS_BASE64:
        required: true
      SIGNING_STORE_PASSWORD:
        required: true
      SIGNING_KEY_ALIAS:
        required: true
      SIGNING_KEY_PASSWORD:
        required: true

jobs:
  build:
    name: Build & Publish to Google Play
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 20
        uses: actions/setup-java@v4
        with:
          java-version: "20"
          distribution: "zulu"

      - name: Setup Ruby & Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Decode Secrets
        run: scripts/decode-secrets.sh
        env:
          PLAY_ACCOUNT_AS_BASE64: ${{ secrets.PLAY_ACCOUNT_AS_BASE64 }}
          KEYSTORE_AS_BASE64: ${{ secrets.KEYSTORE_AS_BASE64 }}
          GOOGLE_SERVICES_FILE_AS_BASE64: ${{ secrets.GOOGLE_SERVICES_FILE_AS_BASE64 }}

      - name: Install Fastlane Dependencies
        working-directory: android
        run: bundle install

      - name: Build & Publish to Google Play
        working-directory: android
        run: bundle exec fastlane deploy
        env:
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
