name: iOS bump version

on:
  workflow_call:
    inputs:
      podSpecFilePath:
        default: 'REES46.podspec'
        type: string
        required: false
        description: File path to podspec file
      appId:
        required: true
        type: string
        description: App token for committing changes

    secrets:
      cocoapodsToken:
        description: Cocoapods token
        required: true
      appSecret:
        description: App secret for committing changes
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}

      - name: Bump version
        env:
          FILE_PATH: ${{ inputs.podSpecFilePath }}
        id: version
        run: |
          current_version=$(awk -F"'" '/s.version *=/ {print $2}' "$FILE_PATH")
          IFS='.' read -r major minor patch <<< "$current_version"
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"
          sed -i '' "s/$current_version/$new_version/" "$FILE_PATH"
          echo "version=$new_version" >> $GITHUB_OUTPUT

      - name: Commit changes
        id: committer
        uses: planetscale/ghcommit-action@v0.1.44
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
        with:
          repo: ${{ github.repository }}
          branch: master
          commit_message: 'chore(common): version bump to ${{ steps.version.outputs.version }}'
          file_pattern: '*.podspec'
