name: Reusable iOS TestFlight Publish

env:
  WORKFLOW_TMP_PATH: tmp/workflow
  WORKFLOW_REPO: 'rees46/workflow'
  ARCHIVE_EXPORT_PATH: './build/exported-app'
  EXPORT_OPTIONS_PLIST_PATH: './ExportOptions.plist'
  PROPERTIES_FILE: 'version.properties'
  ARCHIVE_PATH: build/demo-store-ios.xcarchive

on:
  workflow_call:
    inputs:
      xcworkspace:
        required: true
        type: string
      scheme:
        required: true
        type: string
      codeSignIdentity:
        required: true
        type: string
      developmentTeam:
        required: true
        type: string
      provisioningProfileSpecifier:
        required: true
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_PRIVATE_KEY:
        required: true
      APP_STORE_CONNECT_API_KEY_ID:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_KEY:
        required: true
        description: base64 string
      IOS_CERTIFICATE_P12:
        required: true
        description: base64 string
      IOS_CERTIFICATE_PASSWORD:
        required: true
      IOS_PROVISIONING_PROFILE:
        required: true
        description: base64 string

jobs:
  prepare_build_upload:
    runs-on: macos-latest
    concurrency:
      group: ios-publish-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WORKFLOW_REPO }}
          path: ${{ env.WORKFLOW_TMP_PATH }}

      - uses: rees46/workflow/.github/actions/js/prepare-js@master
        with:
          nodeVersion: 22
          workingDirectory: ${{ env.WORKFLOW_TMP_PATH }}

      - name: Check workflow variables
        uses: rees46/workflow/.github/actions/publish/prepare-testflight@master
        with:
          secretsJson: ${{ toJSON(secrets) }}

      - name: Prepare ios enveronment
        uses: rees46/workflow/.github/actions/ios/prepare-publish@master
        with:
          iosCertificateP12Base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12Password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          provisioningProfileBase64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          certificatePassword: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          appStoreConnectApiKeyId: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appStoreConnectApiKey: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Build ios
        uses: rees46/workflow/.github/actions/ios/build@master
        with:
          appStoreConnectApiKeyId: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appStoreConnectIssuerId: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          archivePath: ${{ env.ARCHIVE_PATH }}
          xcworkspace: ${{ inputs.xcworkspace }}
          scheme: ${{ inputs.scheme }}
          codeSignIdentity: ${{ inputs.codeSignIdentity }}
          developmentTeam: ${{ inputs.developmentTeam }}
          provisioningProfileSpecifier: ${{ inputs.provisioningProfileSpecifier }}

      - name: Archive ios
        uses: rees46/workflow/.github/actions/ios/archive@master
        with:
          archivePath: ${{ env.ARCHIVE_PATH }}
          exportOptionsPlistPath: ${{ env.EXPORT_OPTIONS_PLIST_PATH }}
          archiveExportPath: ${{ env.ARCHIVE_EXPORT_PATH }}

      - name: Upload to testflight
        uses: rees46/workflow/.github/actions/publish/publish-testflight@master
        with:
          archiveExportPath: ${{ env.ARCHIVE_EXPORT_PATH }}
          appStoreConnectIssuerId: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          appStoreConnectApiKeyId: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appStoreConnectApiKey: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          scheme: ${{ inputs.scheme }}
