name: Reusable repository synchronization

env:
  WORKFLOW_REPO: "rees46/workflow"
  WORKFLOW_TMP_PATH: tmp/workflow/
  TARGET_TMP_PATH: tmp/target/
  SOURCE_TMP_PATH: tmp/source/
#
on:
  workflow_call:
    secrets:
      appSecret:
        description: App secret for committing changes
        required: true
    inputs:
      appId:
        description: App ID for committing and pushing
        required: true
        type: string
      replacements:
        description: Replacements
        required: true
        type: string
      targetRepository:
        description: Target repository to sync
        required: true
        type: string
#       appId:
#         type: string
#         required: true
#       targetRepository:
#         type: string
#         required: true
#       repositoryOwner:
#         type: string
#         required: true
#       replacementDirnames:
#         type: string
#       replacementFilenames:
#         type: string
#       syncIgnore:
#         type: string
#         required: true
#         description: list of files to exclue, separated by ','
#         default: ".git,.idea,LICENSE,"
#       replacementExtentions:
#         type: string
#         required: true
#         description: list of extentions to replace, separated by ','
#         default: "*.ts,*.sh,*.yaml"
#       replacementContents:
#         type: string
#         required: true
#         description: list of contents to replace, separated by ',' and '|' - separate source target content\
#         default: "source:content:1|target:conten:1,source-content-1|target-content-1"
#       reviewerUsername:
#         description: PullRequest reviewer username
#         type: string
#         required: false
#         default: TorinAsakura
#     secrets:
#       privateKey:
#         required: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # TODO to prepare sync action
      - uses: actions/create-github-app-token@v1
        id: appTokenStep
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}
          # owner: ${{ inputs.repositoryOwner }}

      - name: Checkout source repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.SOURCE_TMP_PATH }}
          token: ${{ steps.appTokenStep.outputs.token }}

      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          path: ${{ env.TARGET_TMP_PATH }}
          token: ${{ steps.appTokenStep.outputs.token }}
          repository: ${{inputs.targetRepository}}

      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WORKFLOW_REPO }}
          # path: ${{ env.WORKFLOW_TMP_PATH }}
          path: ${{ env.WORKFLOW_TMP_PATH }}
          # TODO rm
          ref: refactor/ios-sync-workflow

      # TODO uncomment
      # - uses: rees46/workflow/.github/actions/js/prepare-js@master
      - uses: rees46/workflow/.github/actions/js/prepare-js@refactor/ios-sync-workflow
        with:
          nodeVersion: 22
          workingDirectory: ${{ env.WORKFLOW_TMP_PATH }}

      - name: Debug tmp absolute
        run: |
          ABSOLUTE_PATH="$GITHUB_WORKSPACE/$TARGET_TMP_PATH"
          cd "$ABSOLUTE_PATH" && ls -a

      - name: Clean target directory
        working-directory: ${{ env.WORKFLOW_TMP_PATH }}
        run: |
          TARGET_TMP_ABS_PATH="$GITHUB_WORKSPACE/${{ env.TARGET_TMP_PATH }}"
          yarn workspace @scripts/clean-directory process '${{ inputs.replacements }}' "$TARGET_TMP_ABS_PATH"

      - name: Debug tmp absolute
        run: |
          ABSOLUTE_PATH="$GITHUB_WORKSPACE/$TARGET_TMP_PATH"
          cd "$ABSOLUTE_PATH" && ls -a

      # - uses: rees46/workflow/.github/actions/utils/fs/sync-dirs@master
      - uses: rees46/workflow/.github/actions/utils/fs/sync-dirs@refactor/ios-sync-workflow
        with:
          targetDirectory: ${{ env.TARGET_TMP_PATH }}
          sourceDirectory: ${{ env.SOURCE_TMP_PATH }}

      - name: Process replacements
        working-directory: tmp/workflow
        run: |
          # TODO to prepare sync
          ABSOLUTE_PATH="$GITHUB_WORKSPACE/${{ env.TARGET_TMP_PATH }}"
          yarn workspace @scripts/repo-replacement process '${{ inputs.replacements }}' "$ABSOLUTE_PATH"

      - name: Debug
        run: git status

      - name: Debug
        run: git diff
#       - uses: rees46/workflow/.github/actions/github/pull-request/get-last-author@master
#         id: lastPrAuthorStep
#         with:
#           githubToken: ${{ steps.appTokenStep.outputs.token }}
#
#       - uses: rees46/workflow/.github/actions/github/utils/get-new-branch-name@master
#         id: newBranchNameStep
#
#       - uses: rees46/workflow/.github/actions/github/checkout/new-branch@master
#         with:
#           branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
#
#       - uses: rees46/workflow/.github/actions/git/add@master
#         with:
#           excludeTmp: true
#
#       - uses: rees46/workflow/.github/actions/github/commit/create@master
#         with:
#           branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
#           githubToken: ${{ steps.appTokenStep.outputs.token }}
#           targetRepository: ${{ inputs.targetRepository }}
#
#       - uses: rees46/workflow/.github/actions/github/pull-request/create@master
#         with:
#           reviewerUsername: ${{ inputs.reviewerUsername }}
#           githubToken: ${{ steps.appTokenStep.outputs.token }}
#           lastPrAuthor: ${{ steps.lastPrAuthorStep.outputs.lastPrAuthor }}
#           branchName: ${{ steps.newBranchNameStep.outputs.branchName }}
