name: Reusable JS/TS PR checks

on:
  workflow_call:
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 19 as it is in action cache'
        default: '19'
        required: false
        type: string
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Yarn cache directory
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn config get cacheFolder)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Fetch all branches
        run: git fetch origin "+refs/heads/*:refs/remotes/origin/*"

      - name: Wait before switching branch
        run: sleep 5

      - name: Switch branch
        run: |
          git switch ${{ github.head_ref }}

      - name: Install
        run: yarn install --inline-builds

      - name: Lint
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run lint

      - name: Test
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run test

      - name: Build
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run build
