name: Reusable JS/TS version bump & create PR

on:
  workflow_call:
    inputs:
      appId:
        description: 'github app id'
        required: true
        type: string
      node-version:
        description: 'Node version to run this workflow. Default: 19 as it is in action cache'
        default: '22'
        required: false
        type: string
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false
      reviewerUsername:
        description: Working direction for action
        default: ./
        type: string
        required: false
    secrets:
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Start JS action
        id: start
        # TODO uncomment
        # uses: rees46/workflow/.github/actions/js/start-js@master
        uses: rees46/workflow/.github/actions/js/start-js@feat/reusable-js-version
        with:
          appId: ${{ inputs.appId }}
          appSecret: ${{ secrets.appSecret }}

      - name: Find last tag commit
        id: lastTagCommit
        # TODO uncomment
        # uses: rees46/workflow/.github/actions/git/find-last-tag-commit@master
        uses: rees46/workflow/.github/actions/git/find-last-tag-commit@feat/reusable-js-version

      - name: Bump version
        if: ${{ !contains(github.event.pull_request.title, 'revert') && !contains(github.event.pull_request.title, 'chore') }}
        uses: rees46/workflow/.github/actions/js/version-js@master
        with:
          checkChanges: 'false'
          private: 'true'
          token: ${{ steps.start.outputs.token }}
          baseCommit: ${{ steps.lastTagCommit.outputs.lastTagCommit }}
          exclude: '.'

      - name: Generate changelog
        working-directory: ${{ inputs.workingDirectory }}
        env:
          GITHUB_TOKEN: ${{ inputs.token }}
          BASE_COMMIT: ${{ steps.lastTagCommit.outputs.lastTagCommit }}
          EXCLUDE: ${{ inputs.exclude }}
        run: yarn workspaces foreach --since=$BASE_COMMIT^ --exclude=$EXCLUDE -vp --jobs=2 run changelog
        shell: bash

      - name: Debug git diff
        run: |
          git diff

      - uses: codfish/semantic-release-action@v3
        id: semanticReleaseStep
        env:
          GH_TOKEN: ${{ inputs.githubToken || steps.start.outputs.token || secrets.GITHUB_TOKEN }}

      - name: Check release published
        shell: bash
        run: |
          if [ "${NEW_RELEASE_PUBLISHED}" != "true" ]; then
            echo "New release not published, exit"
            exit 1
          fi

      - uses: rees46/workflow/.github/actions/release/prepare-pr@master
        with:
          reviewerUsername: ${{ inputs.reviewerUsername }}
          githubToken: ${{ steps.start.outputs.token }}
          releaseVersion: ${{ steps.semanticReleaseStep.outputs.release-version }}
