name: Reusable Capistrano

on:
  workflow_call:
    secrets:
      appSecret:
        description: GitHub App private key (PEM) for generating a token
        required: false
      sshAnsibleKey:
        description: SSH key for ansible user
        required: true
      sshRailsKey:
        description: SSH key for rails user
        required: true
      vpnConfig:
        description: VPN config
        required: true
    inputs:
      clusters:
        description: Clusters in 'cluster1 cluster2' format
        required: true
        type: string
      appId:
        description: GitHub App ID for generating a token
        required: false
        type: string
      rubyVersion:
        description: Ruby version to use
        default: '2.7.5'
        type: string
        required: false

jobs:
  run:
    permissions: read-all
    runs-on: ubuntu-latest

    steps:
      - id: app-token
        if: ${{ inputs.appId }}
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}
          owner: ${{ github.repository_owner }}

      - uses: actions/checkout@v6
        with:
          submodules: 'true'
          token: ${{ steps.app-token.outputs.token || github.token }}

      - uses: webfactory/ssh-agent@25fcd78aa32202988cb0209b14c32ea6fa0288b9
        with:
          ssh-private-key: |
            ${{ secrets.sshAnsibleKey }}
            ${{ secrets.sshRailsKey }}

      - name: Set up ssh config
        run: |
          echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.rubyVersion }}
          bundler-cache: true

      - name: Connect to VPN
        env:
          CONFIG: ${{ secrets.vpnConfig }}
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends openvpn openvpn-systemd-resolved
          echo "$CONFIG" > ../vpn_config.ovpn

          sudo openvpn --config ../vpn_config.ovpn --daemon

          echo "Waiting for VPN connection..."

          for i in {1..15}; do
            if ip a | grep -q "tun0"; then
              echo "VPN connected successfully!"
              exit 0
            fi
            echo "Waiting for VPN to establish (attempt $i)..."
            sleep 1
          done

          echo "Failed to connect to VPN."
          exit 1

      - name: Deploy clusters
        run: |
          failed=0

          for CLUSTER in ${{ inputs.clusters }}; do
            echo "::group::Deploy $CLUSTER"
            if ! bundle exec cap "$CLUSTER" deploy; then
              failed=1
            fi
            echo "::endgroup::"
          done

          exit "$failed"
