# action uses codfish/semantic-release-action and for correct work needs .releaserc.yml in project root with @semantic-release/exec + prepareCmd on config for correct bump work.

name: Reusable version bump

on:
  workflow_call:
    inputs:
      appId:
        required: true
        type: string
        description: App token for committing changes
      reviewerUsername:
        required: false
        type: string
        description: Pull request reviewer
        default: nelfimov

    secrets:
      appSecret:
        description: App secret for committing changes
        required: true
      githubToken:
        description: Github app token
        required: false

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          owner: ${{ github.repository_owner }}
          token: ${{ steps.app-token.outputs.token }}
          fetch-depth: 0

      - uses: docker://ghcr.io/codfish/semantic-release-action:v3
        id: semanticReleaseStep
        env:
          GH_TOKEN: ${{ secrets.githubToken || steps.app-token.outputs.token || secrets.GITHUB_TOKEN }}
        with:
          additional-packages: |
            ['@semantic-release/exec', '@semantic-release/git']

      - uses: rees46/workflow/.github/actions/release/prepare-pr@master
        with:
          reviewerUsername: ${{ inputs.reviewerUsername }}
          githubToken: ${{ steps.app-token.outputs.token }}
          releaseVersion: ${{ steps.semanticReleaseStep.outputs.release-version }}
