name: Reusable Android SDK version

on:
  workflow_call:
    outputs:
      committed:
        description: Have the changes in version been commited?
        value: ${{ jobs.run.outputs.committed }}
    inputs:
      PROPERTIES_FILE:
        default: gradle.properties
        type: string
        description: Relative file path for putting in secrets
        required: false
      SIGNING_SECRET_KEY_RING_FILE:
        default: com.rees46.key.gpg
        type: string
        description: Location and name for signature file
        required: false
      SIGNING_SECRET_KEY_RING_FILE_LOCATION:
        type: string
        description: Location and name for signature file
        required: true
      GRADLE_VERSION:
        default: 8.2
        type: number
        required: false
      appId:
        required: true
        type: string
        description: 'App ID for committing and pushing'
    secrets:
      OSSRH_USERNAME:
        required: true
      OSSRH_PASSWORD:
        required: true
      SIGNING_KEY_ID:
        required: true
      SIGNING_PASSWORD:
        required: true
      SONATYPE_REES46:
        required: true
      SONATYPE_PERSONACLICK:
        required: true
      SIGNING_KEY_FILE_AS_BASE64_STRING:
        required: true
      appSecret:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.committer.outputs.committed }}

    steps:

      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
          token: ${{ steps.app-token.outputs.token }}

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: ${{ inputs.GRADLE_VERSION }}

      - name: Append secrets to gradle.properties
        env:
          PROPERTIES_FILE: ${{ inputs.PROPERTIES_FILE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_SECRET_KEY_RING_FILE: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE }}
          SONATYPE_REES46: ${{ secrets.SONATYPE_REES46 }}
          SONATYPE_PERSONACLICK: ${{ secrets.SONATYPE_PERSONACLICK }}
        run: |
          echo "ossrhUsername=$OSSRH_USERNAME" >> $PROPERTIES_FILE
          echo "ossrhPassword=$OSSRH_PASSWORD" >> $PROPERTIES_FILE
          echo "signing_keyId=$SIGNING_KEY_ID" >> $PROPERTIES_FILE
          echo "signing_password=$SIGNING_PASSWORD" >> $PROPERTIES_FILE
          echo "signing_secretKeyRingFile=$SIGNING_SECRET_KEY_RING_FILE" >> $PROPERTIES_FILE
          echo "sonatype_rees46=$SONATYPE_REES46" >> $PROPERTIES_FILE
          echo "sonatype_personaclick=$SONATYPE_PERSONACLICK" >> $PROPERTIES_FILE
          echo "Updated $PROPERTIES_FILE"

      - name: Decode signing key file
        uses: timheuer/base64-to-file@v1.2
        id: service_account_json_file
        with:
          fileName: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE }}
          fileDir: ${{ inputs.SIGNING_SECRET_KEY_RING_FILE_LOCATION }}
          encodedString: ${{ secrets.SIGNING_KEY_FILE_AS_BASE64_STRING }}

      - name: Patch version
        run: ./gradlew personalizatio-sdk:increaseVersionCode

      - name: GitSign
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit changes
        id: committer
        uses: EndBug/add-and-commit@v9
        with:
          commit: -S
          default_author: github_actions
          author_email: github-bot@rees46.com
          message: 'chore(common): version'
          add: 'personalizatio-sdk'
