name: Reusable iOS TestFlight Publish

env:
  WORKFLOW_TMP_PATH: tmp/workflow
  WORKFLOW_REPO: "rees46/workflow"
  ARCHIVE_EXPORT_PATH: "./build/exported-app"
  EXPORT_OPTIONS_PLIST_PATH: "./ExportOptions.plist"
  PROPERTIES_FILE: "version.properties"

on:
  workflow_call:
    inputs:
      xcworkspace:
        required: true
        type: string
      scheme:
        required: true
        type: string
      codeSignIdentity:
        required: true
        type: string
      developmentTeam:
        required: true
        type: string
      provisioningProfileSpecifier:
        required: true
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_PRIVATE_KEY:
        required: true
      APP_STORE_CONNECT_API_KEY_ID:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_KEY:
        required: true
        description: base64 string
      IOS_CERTIFICATE_P12:
        required: true
        description: base64 string
      IOS_CERTIFICATE_PASSWORD:
        required: true
      IOS_PROVISIONING_PROFILE:
        required: true
        description: base64 string

jobs:
  prepare_build_upload:
    runs-on: macos-latest
    concurrency:
      group: ios-publish-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WORKFLOW_REPO }}
          path: ${{ env.WORKFLOW_TMP_PATH }}
          # TODO remove
          ref: feat/version-workflow

      - uses: rees46/workflow/.github/actions/js/prepare-js@master
        with:
          nodeVersion: 22
          workingDirectory: ${{ env.WORKFLOW_TMP_PATH }}

      - name: Check workflow variables
        # TODO to master
        # uses: rees46/workflow/.github/actions/utils/check-vars@master
        uses: rees46/workflow/.github/actions/utils/check-vars@feat/version-workflow
        with:
          workflowDirectory: ${{ env.WORKFLOW_TMP_PATH }}
          varsJson: ${{ toJSON(secrets) }}
          requiredVars:
            "GITHUB_APP_ID,GITHUB_APP_PRIVATE_KEY,APP_STORE_CONNECT_API_KEY_ID,APP_STORE_CONNECT_ISSUER_ID,APP_STORE_CONNECT_API_KEY,IOS_CERTIFICATE_P12,IOS_CERTIFICATE_PASSWORD,IOS_PROVISIONING_PROFILE"

            # TODO rm tmp directory

      # - name: Checkout repository
      #   uses: actions/checkout@v4
      #   with:
      #     fetch-depth: 0
      #
      # - name: Install the Apple certificate & provisioning profile & P8
      #   env:
      #     BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_CERTIFICATE_P12 }}
      #     P12_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      #     BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
      #     KEYCHAIN_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      #     APP_STORE_CONNECT_API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     APP_STORE_CONNECT_API_KEY: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
      #   run: |
      #     # prepare dirs
      #     mkdir -p private_keys
      #
      #     # create variables
      #     CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
      #     PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
      #     KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
      #     AUTH_KEY_PATH="private_keys/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8"
      #
      #     # apply auth key
      #     echo -n "$APP_STORE_CONNECT_API_KEY" | base64 --decode -o $AUTH_KEY_PATH
      #
      #     # import certificate and provisioning profile from secrets
      #     echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
      #     echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
      #
      #     # create temporary keychain
      #     security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      #     security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
      #     security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      #
      #     # import certificate to keychain
      #     security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
      #     security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
      #     security list-keychain -d user -s $KEYCHAIN_PATH
      #
      #     # apply provisioning profile
      #     mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
      #     cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
      #
      # - name: Pod install
      #   run: |
      #     pod install
      #
      # - name: Build and Archive
      #   env:
      #     API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      #   run: |
      #     ARCHIVE_PATH=$PWD/build/demo-store-ios.xcarchive
      #
      #     xcrun xcodebuild \
      #       -workspace "${{ inputs.xcworkspace }}" \
      #       -scheme "${{ inputs.scheme }}" \
      #       -configuration AppStoreDistribution \
      #       -sdk iphoneos \
      #       -parallelizeTargets \
      #       -showBuildTimingSummary \
      #       -disableAutomaticPackageResolution \
      #       -archivePath "$ARCHIVE_PATH" \
      #       archive \
      #       CODE_SIGN_STYLE=Manual \
      #       CODE_SIGN_IDENTITY="${{ inputs.codeSignIdentity }}" \
      #       DEVELOPMENT_TEAM="${{ inputs.developmentTeam }}" \
      #       PROVISIONING_PROFILE_SPECIFIER="${{ inputs.provisioningProfileSpecifier }}" \
      #       OTHER_CODE_SIGN_FLAGS="--deep"
      #
      #     xcrun xcodebuild \
      #       -exportArchive \
      #       -archivePath "$ARCHIVE_PATH" \
      #       -exportOptionsPlist "${{ env.EXPORT_OPTIONS_PLIST_PATH }}" \
      #       -exportPath "${{ env.ARCHIVE_EXPORT_PATH }}" \
      #
      # - name: Upload to TestFlight
      #   uses: Apple-Actions/upload-testflight-build@master
      #   with:
      #     app-path: "${{ env.ARCHIVE_EXPORT_PATH }}/${{ inputs.scheme }}.ipa"
      #     issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
