name: Reusable Ansible playbook dry-run

on:
  workflow_call:
    inputs:
      PLAYBOOK_NAME:
        required: true
        type: string
      FOLDER:
        required: true
        type: string
      PLAYBOOKS_PATH:
        required: true
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true

jobs:
  dry-run:
    name: Ansible dry-run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ansible
        uses: alex-oleshkevich/setup-ansible@v1.0.1
        with:
          version: '11'

      - name: Set up ssh
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "StrictHostKeyChecking no" >> ~/.ssh/config
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add ~/.ssh/id_rsa

      - name: Run Ansible for all matched files
        env:
          PLAYBOOKS_PATH: ${{ inputs.PLAYBOOKS_PATH }}
          PLAYBOOK_NAME: ${{ inputs.PLAYBOOK_NAME }}
          FOLDER: ${{ inputs.FOLDER }}
        run: |
          echo "Looking for playbook $PLAYBOOK_NAME under $FOLDER in parent folder $PLAYBOOKS_PATH"

          MATCHED_FILES=$(find $PLAYBOOKS_PATH | grep "$FOLDER" | grep "$PLAYBOOK_NAME")

          echo "$MATCHED_FILES"

          if [ -z "$MATCHED_FILES" ]; then
            echo "No matching files found."

            exit 1
          fi

          for FILE in $MATCHED_FILES; do
            echo "Running ansible-playbook for $FILE"

            cd $(dirname "$FILE")

            ansible-playbook --check --diff --private-key="~/.ssh/id_rsa" "$(basename $FILE)"

            cd "$(git rev-parse --show-toplevel)"
          done
