name: iOS checks

on:
  workflow_call:
    secrets:
      cocoapodsToken:
        description: Cocoapods token
        required: true

jobs:
  run:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - name: Pod install
        working-directory: ./DemoApp
        run: |
          pod cache clean --all
          rm -rf Pods
          rm -rf Pods.xcodeproj
          pod install

      - name: Build
        run: |
          xcodebuild clean build -workspace ./DemoApp/REES46.xcworkspace -scheme REES46Demo \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS=''

      - name: Run tests
        if: always()
        run: |
          xcodebuild clean test -workspace ./DemoApp/REES46.xcworkspace -scheme REES46Demo \
          -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
          CODE_SIGN_IDENTITY='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_ENTITLEMENTS=''

      - name: Lint spec
        if: always()
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod spec lint --allow-warnings

      - name: Lint lib
        if: always()
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.cocoapodsToken }}
        run: pod lib lint --allow-warnings
