name: Reusable version

on:
  workflow_call:
    inputs:
      mergeLabels:
        required: false
        default: automerge
        type: string
        description: PRs with this label will be auto merged.
      mergeMethod:
        required: false
        default: merge
        type: string
        description: Method to merge PRs. Can be "merge", "rebase", "squash"
      mergeDeleteBranch:
        required: false
        default: true
        type: boolean
        description: Should the branch be deleted when PR is merged
      mergeRequiredApprovals:
        required: false
        default: 0
        type: number
        description: How many approvals required for merge
      log:
        required: false
        default: TRACE
        type: number
        description: How many approvals required for merge

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: Auto merge
        uses: gsoc2/automerge-action@v0.16.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_LABELS: ${{ inputs.mergeLabels }}
          MERGE_METHOD: ${{ inputs.mergeMethod }}
          MERGE_DELETE_BRANCH: ${{ inputs.mergeDeleteBranch }}
          MERGE_REQUIRED_APPROVALS: ${{ inputs.mergeRequiredApprovals }}
          LOG: ${{ inputs.log }}
