name: Reusable JS/TS PR checks

on:
  workflow_call:
    inputs:
      app-id:
        description: 'github app id'
        required: true
        type: string
      node-version:
        description: 'Node version to run this workflow. Default: 19 as it is in action cache'
        default: '19'
        required: false
        type: string
      workingDirectory:
        description: Working direction for action
        default: ./
        type: string
        required: false
    secrets:
      private-key:
        required: true

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.workingDirectory }}

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.app-id }}
          private-key: ${{ secrets.private-key }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}

      - name: Prepare JS action
        id: start
        uses: rees46/workflow/.github/actions/js/prepare-js@master
        with:
          nodeVersion: ${{ inputs.node-version }}

      - name: Lint
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run lint

      - name: Test
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run test

      - name: Build
        if: ${{ !cancelled() }}
        env:
          TARGET: ${{ github.base_ref }}
        run: yarn workspaces foreach -vp --since=origin/$TARGET --jobs=2 run build
