name: Reusable iOS TestFlight Publish

env:
  WORKFLOW_TMP_PATH: tmp/workflow
  WORKFLOW_REPO: "rees46/workflow"
  ARCHIVE_EXPORT_PATH: "./build/exported-app"
  EXPORT_OPTIONS_PLIST_PATH: "./ExportOptions.plist"
  PROPERTIES_FILE: "version.properties"
  ARCHIVE_PATH: build/demo-store-ios.xcarchive

on:
  workflow_call:
    inputs:
      xcworkspace:
        required: true
        type: string
      scheme:
        required: true
        type: string
      codeSignIdentity:
        required: true
        type: string
      developmentTeam:
        required: true
        type: string
      provisioningProfileSpecifier:
        required: true
        type: string
    secrets:
      GITHUB_APP_ID:
        required: true
      GITHUB_APP_PRIVATE_KEY:
        required: true
      APP_STORE_CONNECT_API_KEY_ID:
        required: true
      APP_STORE_CONNECT_ISSUER_ID:
        required: true
      APP_STORE_CONNECT_API_KEY:
        required: true
        description: base64 string
      IOS_CERTIFICATE_P12:
        required: true
        description: base64 string
      IOS_CERTIFICATE_PASSWORD:
        required: true
      IOS_PROVISIONING_PROFILE:
        required: true
        description: base64 string

jobs:
  prepare_build_upload:
    runs-on: macos-latest
    concurrency:
      group: ios-publish-${{ github.ref }}
      cancel-in-progress: true
    timeout-minutes: 20

    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v4
        with:
          repository: ${{ env.WORKFLOW_REPO }}
          path: ${{ env.WORKFLOW_TMP_PATH }}
          # TODO remove
          ref: feat/version-workflow

      - uses: rees46/workflow/.github/actions/js/prepare-js@master
        with:
          nodeVersion: 22
          workingDirectory: ${{ env.WORKFLOW_TMP_PATH }}

      - name: Check workflow variables
        # TODO to master
        # uses: rees46/workflow/.github/actions/publish/prepare-testflight@master
        uses: rees46/workflow/.github/actions/publish/prepare-testflight@feat/version-workflow
        with:
          secretsJson: ${{ toJSON(secrets) }}

      - name: Prepare ios enveronment
        # TODO to master
        # uses: rees46/workflow/.github/actions/ios/prepare-publish@master
        uses: rees46/workflow/.github/actions/ios/prepare-publish@feat/version-workflow
        with:
          iosCertificateP12Base64: ${{ secrets.IOS_CERTIFICATE_P12 }}
          p12Password: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          provisioningProfileBase64: ${{ secrets.IOS_PROVISIONING_PROFILE }}
          certificatePassword: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
          appStoreConnectApiKeyId: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appStoreConnectApiKey: ${{ secrets.APP_STORE_CONNECT_API_KEY }}

      - name: Build ios
        # TODO to master
        # uses: rees46/workflow/.github/actions/ios/build@master
        uses: rees46/workflow/.github/actions/ios/build@feat/version-workflow
        with:
          appStoreConnectApiKeyId: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
          appStoreConnectIssuerId: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          archivePath: ${{ env.ARCHIVE_PATH }}
          xcworkspace: ${{ inputs.xcworkspace }}
          scheme: ${{ inputs.scheme }}
          codeSignIdentity: ${{ inputs.codeSignIdentity }}
          developmentTeam: ${{ inputs.developmentTeam }}
          provisioningProfileSpecifier: ${{ inputs.provisioningProfileSpecifier }}

      - name: Archive ios
        # TODO to master
        # uses: rees46/workflow/.github/actions/ios/archive@master
        uses: rees46/workflow/.github/actions/ios/archive@feat/version-workflow
        with:
          archivePath: ${{ env.ARCHIVE_PATH }}
          exportOptionsPlistPath: ${{ env.EXPORT_OPTIONS_PLIST_PATH }}
          archiveExportPath: ${{ env.ARCHIVE_EXPORT_PATH }}

      # - name: Upload to TestFlight
      #   uses: Apple-Actions/upload-testflight-build@master
      #   with:
      #     app-path: "${{ env.ARCHIVE_EXPORT_PATH }}/${{ inputs.scheme }}.ipa"
      #     issuer-id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
      #     api-key-id: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
      #     api-private-key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
