name: Reusable version

on:
  workflow_call:
    outputs:
      committed:
        description: 'Have the changes in version been committed?'
        value: ${{ jobs.run.outputs.committed }}
    inputs:
      node-version:
        description: 'Node version to run this workflow. Default: 18.19 as it is in action cache'
        default: '18.19'
        required: false
        type: string
      appId:
        description: 'App ID for committing and pushing'
        required: true
        type: string
    secrets:
      appSecret:
        required: true

jobs:
  run:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      committed: ${{ steps.committer.outputs.committed }}

    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ inputs.appId }}
          private-key: ${{ secrets.appSecret }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ steps.app-token.outputs.token }}
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install
        run: yarn install --mode=update-lockfile --inline-builds
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: Find Base Commit for master
        id: find_base_commit
        run: |
          echo "Finding base commit between HEAD and origin/master"
          base_commit=$(git log --merges -n 2 --format=format:%H | tail -n 1)
          echo "::set-output name=base_commit::$base_commit"
          echo "Base Commit: $base_commit"

      - name: Version
        run: yarn workspaces foreach --since=${{ steps.find_base_commit.outputs.base_commit }} --no-private --verbose version patch --deferred
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'

      - name: GitSign
        uses: chainguard-dev/actions/setup-gitsign@main

      - name: Commit changes
        if: ${{ !env.ACT }}
        id: committer
        uses: EndBug/add-and-commit@v9
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit: -S
          default_author: github_actions
          author_email: github-bot@rees46.com
          message: 'chore(common): version'
          add: '*.yml'
