name: Read replacements
description: checkout and read replacements by path

inputs:
  appId:
    description: github app id
    required: true
  appSecret:
    description: github app secret
    required: true
  replacementsRepo:
    description: github repository with replacements
    required: false
    default: rees46/infrastructure
  repositoryOwner:
    description: owner of repository with replacements
    required: false
    default: rees46
  replacementsPath:
    description: path to replacements.yml
    required: true

outputs:
  replacements:
    description: replacements in compact json format in string
    value: ${{ steps.getReplacementsStep.outputs.replacements }}

runs:
  using: composite

  steps:
    - uses: actions/create-github-app-token@v1
      id: appTokenStep
      with:
        app-id: ${{ inputs.appId }}
        private-key: ${{ inputs.appSecret }}
        owner: ${{ inputs.repositoryOwner }}

    - name: Checkout target repository
      uses: actions/checkout@v4
      with:
        # TODO rm
        ref: feat/replacements
        token: ${{ steps.appTokenStep.outputs.token }}
        repository: ${{inputs.replacementsRepo}}

    - name: Read replacements from file
      shell: bash
      id: getReplacementsStep
      run: |
        REPLACEMENTS=$(yq eval -o=json . ${{ inputs.replacementsPath }} | jq -c)
        echo "Replacements: $REPLACEMENTS"

        echo "replacements=$REPLACEMENTS" >> $GITHUB_OUTPUT
